alter table PETCLINIC_VISIT add constraint FK_PETCLINIC_VISIT_TREATING_VET foreign key (TREATING_VET_ID) references PETCLINIC_VET(ID);
create index IDX_PETCLINIC_VISIT_TREATING_VET on PETCLINIC_VISIT (TREATING_VET_ID);
